language: c

compiler:
  - gcc

matrix:
  include:
    # Ubuntu Trusty, Xenial and Bionic
    - dist: trusty

    - dist: bionic

    # MacOs
    - os: osx

    # Windows
    # run on git-bash the script bash
    # differ from documentation 'cmake -DCMAKE_INSTALL_PREFIX=%HOMEPATH%\local ..\'
    - os: windows

install: 
  - mkdir build
  - cd build

before_script : cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../

script:
  - make
